### ISSUE TITLE
Marshalled requests for OFX 102 should not include element end tags

### ISSUE THREAD

**Issue by JohnStarich** [aclindsa/ofxgo#18]
The OFX 102 spec is a bit lacking in this area, but it seems that some institutions require ofx elements not include their end tags (aggregates are ok though).

> The key rule of Open Financial Exchange syntax is that each tag is either an element or an aggregate. Data follows its element tag. An aggregate tag begins a compound tag sequence, which must end with a matching tag; for example, `<AGGREGATE> ... </AGGREGATE>`.

From the reading above and my use of the python `ofxclient`, I think always omitting the element end tags should work for all institutions using OFX 102 (maybe all 100-series, but I haven't looked yet).

In my case, USAA doesn't like me using any element end tags. This is my hacky work-around:

```go
var r *ofxgo.Request
b, _ := r.Marshal()

data := b.Bytes()
for _, s := range []string{"DTCLIENT", "DTSTART", "DTEND", "INCLUDE", "USERID", "USERPASS", "LANGUAGE", "ORG", "FID", "APPID", "APPVER", "TRNUID", "BANKID", "ACCTID", "ACCTTYPE"} {
	data = bytes.Replace(data, []byte("</"+s+">"), []byte{}, -1)
}
b = bytes.NewBuffer(data)
```

What do you think would be a good solution to this problem? I briefly looked at your fork of go's xml package, looks like that might be a good place for it. Maybe it could be some kind of encoder option?

**Comment by aclindsa** [comment]
Hah! SGML is a thorn in my side. For the full set of the elements which may be left un-closed with the SGML versions of OFX, see https://github.com/aclindsa/ofxgo/blob/master/leaf_elements.go.

As you've already found, I used a feature of Go's existing XML decoder for parsing SGML responses (though I had to modify it slightly). I don't see any reason my existing fork of the library couldn't be modified further to omit closing tags for the same list from above. I didn't make the similar modification for encoding requests mostly because it seemed like I was going to be able to get away with it, not because I have an issue with doing it.

I believe this modification should be acceptable for all SGML-based OFX versions (i.e. 1xx), and should not need to be USAA-specific.

**Comment by JohnStarich** [comment]
Oh, excellent! I didn't see you had the complete list already 🎉 

Sweet. Yeah, I thought that might've happened 👍 Sometimes it's best to just get things working first! 😉 

Nice, ok. I'm not very familiar with the Go XML encoder, but I can give it a shot if you like?

**Comment by aclindsa** [comment]
@JohnStarich Absolutely feel free to give it a shot!

**Comment by JohnStarich** [comment]
To my surprise, this ended up being pretty easy! (unless I missed something 😨)
I've pushed a [new PR](https://github.com/aclindsa/xml/pull/1) up for your review in the `xml` repo.

I think the calling syntax in `ofxgo` would look super similar to how the decoder is set up today.

**Comment by JohnStarich** [comment]
Thanks for the quick review/merge! 😄 
I've put up a PR for the last piece, too https://github.com/aclindsa/ofxgo/pull/19

**Comment by JohnStarich** [comment]
friendly poke 👉 @aclindsa

**Comment by JohnStarich** [comment]
Thanks a bunch @aclindsa! 🎉
