### ISSUE TITLE
Pending transactions missing from query responses

### ISSUE THREAD

**Issue by jwaggs** [aclindsa/ofxgo#22]
I'm currently using my personal Chase Bank checking, savings and credit accounts to play with this package.  Most things are working as expected however I am not able to get my statement balances and transactions to be as up to date as I would like. It appears the responses ignore pending charges entirely regardless of whether the `IncludePending` flag is set to true. Have you seen this behavior before? I have to imagine retrieving pending charges would be supported by chase but I could be wrong.

**Comment by aclindsa** [comment]
Have you been able to retrieve Chase's pending transactions via OFX with another piece of software? I have not, and I suspect it is because Chase does not support this.

Also, to clarify, have you inspected the raw OFX response? There's not much I know to do if we're setting `IncludePending` properly and Chase simply isn't returning the transactions. My only hope would be that somehow they're in the raw OFX return and we're not parsing them properly.

**Comment by jwaggs** [comment]
This is my first time attempting to retrieve my Chase transactions, so unfortunately I don't have a reference to determine whether this is simply a "feature" of chase or a shortcoming of the library. That being said, by visually parsing the raw response content, it appears on the surface that chase simply does not include pending data. It also appears that all updates to balances and transactions are made at midnight UTC time. I'd love to be proven wrong here though.

**Comment by aclindsa** [comment]
I did a brief search, and found some folks saying Quicken also doesn't download pending transactions from Chase (purportedly by design):

https://community.quicken.com/discussion/7848030/download-of-chase-pending-transactions

Unfortunately I don't see any evidence that this is something ofxgo can support. Unless you have some evidence that it can be supported, I'm tempted to close this issue. Any comments to the contrary?

**Comment by jwaggs** [comment]
I agree with your assessment. All of my research is pointing to the same conclusion. Feel free to ping me if you ever discover otherwise! For the sake of this issue though we can consider matters closed.
