### ISSUE TITLE
XML syntax error on line 1: element <MESSAGE> closed by </STATUS>

### ISSUE THREAD

**Issue by lgwieser** [aclindsa/ofxgo#54]
Response from Fidelity:

`<?xml version="1.0" encoding="UTF-8" standalone="no"?><?OFX OFXHEADER="200" VERSION="203" SECURITY="NONE" OLDFILEUID="NONE" NEWFILEUID="NONE"?><OFX><SIGNONMSGSRSV1><SONRS><STATUS><CODE>0</CODE><SEVERITY>INFO</SEVERITY><MESSAGE>SUCCESS</MESSAGE></STATUS><DTSERVER>20230906145854.013[-4:EDT]</DTSERVER><LANGUAGE>ENG</LANGUAGE><FI><ORG>fidelity.com</ORG><FID>7776</FID></FI></SONRS></SIGNONMSGSRSV1><BANKMSGSRSV1><STMTTRNRS><TRNUID>553f36a9-b492-8e8f-b86f-6284b76597f9<STATUS><CODE>0<SEVERITY>INFO<MESSAGE>SUCCESS</STATUS>`...

At the tail end of that ... `<MESSAGE>`is indeed implicitly closed by `</STATUS>`. Is this a parsing problem? Or is Fidelity's response incorrectly formatted?

**Comment by aclindsa** [comment]
I believe this response is invalid. My understanding is that for OFX version 2xx, the SGML-style self-closing tags are not allowed. It's also strange to me that you're seeing this behavior with Fidelity - I have two Fidelity accounts (an HSA and a 401k) and both of them close the MESSAGE tag like the following in my downloads from them: `<STATUS><CODE>0</CODE><SEVERITY>INFO</SEVERITY><MESSAGE>SUCCESS</MESSAGE></STATUS>`.

**Comment by lgwieser** [comment]
This is a Bank account (cash management) not an Investment account. After the malformed `<MESSAGE>` is:

`<STMTRS><CURDEF>USD<BANKACCTFROM><BANKID>[deleted]<ACCTID>[deleted]<ACCTTYPE>SAVINGS</BANKACCTFROM><BANKTRANLIST><DTSTART>20230827145852.612[-4:EDT]<DTEND>20230905145854.015[-4:EDT]<STMTTRN><TRNTYPE>DEBIT                                            <DTPOSTED>20230905000000.000` ...

And all the expected `<STMTTRN>`'s after that. But the client.Request() doesn't parse them since it gets confused by the malformed `<MESSAGE>`.

Suggestions on a fix? I can imagine either:

1.  Relaxed XML parsing around `<MESSAGE>` in your xml fork.
2. Brute force. Use client.RequestNoParse(); edit the response to close the `<MESSAGE>` tag and then pass that to ParseResponse() ?
3. Other thoughts?

**Comment by aclindsa** [comment]
> But the client.Request() doesn't parse them since it gets confused by the malformed <MESSAGE>.

Right, because its not valid OFX!

> 1. Relaxed XML parsing around `<MESSAGE>` in your xml fork.

One thing you could try is hacking the code to treat the XML OFX versions as SGML, because this is basically exactly what I do for . In particular, you can see at https://github.com/aclindsa/ofxgo/blob/master/response.go#L303 that the assignment `decoder.AutoCloseAfterCharData = ofxLeafElements` only takes place if we are *not* using an XML version of OFX (`if !xmlVersion`). In your local branch, you could try removing the `if` statement surrounding lines 302 and 303 so that they were always executed. Executing those two lines should cause the XML parser to auto-close leaf tags in the way the SGML-based OFX variants allow. (This doesn't seem like a solution I would want upstream, though)

> 2. Brute force. Use client.RequestNoParse(); edit the response to close the <MESSAGE> tag and then pass that to ParseResponse() ?
> 3. Other thoughts?

One possibility would be to split the code for ParseResponse and DecodeResponse into two versions each (I think if you structured it right you wouldn't even need to duplicate code because one could just call the other). In each case, one version would have the same call signature as the current functions. But you could add another version of each which effectively made the change above to make the parsing of XML versions more similar to that of the SGML OFX versions. Then... you could take it a step farther and make a 'Client' (see the code in client.go that makes Vanguard- and Discover-specific clients) that selectively used your code only for Fidelity. Though I'm not exactly sure the best way to determine when to use it and when not to for Fidelity, since it doesn't seem to always be needed?

**Comment by aclindsa** [comment]
> because this is basically exactly what I do for

This should have said "...because this is basically exactly what I do for the the older SGML-based OFX versions."

**Comment by lgwieser** [comment]
Since your Fidelity accounts parse just fine I did some additional testing. 

I was requesting transactions for a "Cash Management Account" so I used Bank StatementRequest and StatementResponse. Fidelity's OFX servers responded with malformed OFX above. (But the transaction list returned is fine.)

If I request transactions for the same account but use InvStatementRequest and InvStatementResponse I get a properly constructed header with the `<MESSAGE>` tag appropriately closed.

Odd. Interesting. The joy of OFX.

**Comment by aclindsa** [comment]
> If I request transactions for the same account but use InvStatementRequest and InvStatementResponse I get a properly constructed header with the `<MESSAGE>` tag appropriately closed.

Hahahahaha. Ahhhh, you have to love the inconsistency. I wonder if this means Quicken/Intuit uses InvStatementRequest for all requests to Fidelity or something, and it is therefore the more well-tested endpoint? Oh well, I'm glad you found something that is working for you.
